<?php

// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Automatically generated strings for Moodle installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['cannotcreatedboninstall'] = '<p> ไม่สามารถสร้างฐานข้อมูล </p>
<p> ฐานข้อมูลที่ระบุไม่มีอยู่และผู้ที่ได้รับไม่ได้รับอนุญาตในการสร้างฐานข้อมูล </p>
<p> ผู้ดูแลเว็บไซต์ควรตรวจสอบการกำหนดค่าฐานข้อมูล </p>';
$string['cannotcreatelangdir'] = 'ไม่สามารถสร้าง lang directory';
$string['cannotcreatetempdir'] = 'ไม่สามารถสร้าง temp directory';
$string['cannotdownloadcomponents'] = 'ไม่สามารถดาวน์โหลดส่วนประกอบ';
$string['cannotdownloadzipfile'] = 'ไม่สามารถดาวน์โหลดไฟล์ ZIP';
$string['cannotfindcomponent'] = 'ไม่พบส่วนประกอบ';
$string['cannotsavemd5file'] = 'ไม่สามารถบันทึกแฟ้ม md5';
$string['cannotsavezipfile'] = 'ไม่สามารถบันทึกไฟล์ ZIP';
$string['cannotunzipfile'] = 'ไม่สามารถเปิดเครื่องรูดแฟ้ม';
$string['componentisuptodate'] = 'ชิ้นส่วนที่เป็น up-to-date';
$string['dmlexceptiononinstall'] = '<p> ข้อผิดพลาดที่ฐานข้อมูลเกิดขึ้น [{$a->errorcode}] <br /> {$a->debuginfo} </p>';
$string['downloadedfilecheckfailed'] = 'ตรวจสอบไฟล์ที่ดาวน์โหลดมาล้มเหลว';
$string['invalidmd5'] = 'md5 ไม่ถูกต้อง';
$string['missingrequiredfield'] = 'เขตข้อมูลที่ต้องการจะหายไป';
$string['remotedownloaderror'] = 'ดาวน์โหลดของส่วนประกอบไปยังเซิร์ฟเวอร์ของคุณล้มเหลวโปรดยืนยันการตั้งค่าพร็อกซี่ขยาย PHP cURL แนะนำเป็นอย่างยิ่ง.<br /><br />You must download the <a href="{$a->url}">{$a->url}</a> file manually, copy it to "{$a->dest}" in your server and unzip it there.';
$string['wrongdestpath'] = 'เส้นทางปลายทางผิด';
$string['wrongsourcebase'] = 'แหล่งที่มาของฐานผิด URL';
$string['wrongzipfilename'] = 'ZIP ไฟล์ชื่อผิด';
