<?php

// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Automatically generated strings for Moodle installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['admindirname'] = 'ไดเรกทอรี admin';
$string['availablelangs'] = 'ภาษาทั้งหมด';
$string['chooselanguagehead'] = 'เลื่อกภาษา';
$string['chooselanguagesub'] = 'กรุณาเลือกภาษาที่ใช้ในการติดตั้งเท่านั้น คุณจะสามารถเลือกตั้งค่าภาษาสำหรับเว็บไซต์และสำหรับสมาชิกแต่ละคนในหน้าจอต่อไป';
$string['clialreadyconfigured'] = 'config.php แฟ้มการกำหนดค่าที่มีอยู่แล้ว โปรดใช้ธุรการ / CLI / install_database.php การติดตั้ง Totara สำหรับไซต์นี้';
$string['clialreadyinstalled'] = 'config.php แฟ้มการกำหนดค่าที่มีอยู่แล้ว โปรดใช้ธุรการ / CLI / install_database.php ที่จะอัพเกรด Totara สำหรับไซต์นี้';
$string['configfilenotwritten'] = 'ตัวติดตั้งอัตโนมัติไม่สามารถสร้างไฟล์ config.php ได้ อาจเป็นเพราะว่าไม่สามารถเขียนลงไดเรกทอรี moodle ได้ คุณสามารถสร้างไฟล์ดังกล่าวได้เองโดยการก้อปปี้โค้ดต่อไปนี้ลงในไฟล์ที่ต้องการสร้างใหม่';
$string['configfilewritten'] = 'สร้าง config.php เรียบร้อยแล้ว';
$string['configurationcompletesub'] = 'Totara ทำการบันทึกไฟล์การตั้งค่าลงในโฟลเดอร์ moodle หลังจากทำการติดตั้ง';
$string['databasehost'] = 'ที่เก็บฐานข้อมูล:';
$string['databasename'] = 'ชื่อฐานข้อมูล:';
$string['databasetypehead'] = 'เลือกโปรแกรมควบคุมฐานข้อมูล';
$string['dataroot'] = 'ไดเรกทอรีข้อมูล';
$string['datarootpermission'] = 'ข้อมูลที่สาระบบได้รับอนุญาต';
$string['dbprefix'] = 'คำนำหน้าตาราง (Table Prefix)';
$string['dirroot'] = 'Totara ไดเรกทอรี';
$string['environmenthead'] = 'ตรวจสอบความพร้อมของระบบ';
$string['errorsinenvironment'] = 'ข้อผิดพลาดในสภาพแวดล้อม! n';
$string['installation'] = 'การติดตั้ง';
$string['langdownloaderror'] = 'ภาษา "{$a}" ไม่ได้รับการติดตั้ง กระบวนการติดตั้งจะดำเนินไปด้วยภาษาอังกฤษ';
$string['memorylimithelp'] = '<p>ค่าความจำสูงสุดของเซิร์ฟเวอร์ของคุณตั้งไว้ที่  {$a}</p>

<p>ความจำดังกล่าวมีค่าน้อยไปค่ะอาจทำให้มีปัญหาในการใช้งาน moodle ในภายหลังโดยเฉพาะเมื่อคุณใช้โมดูลหลาย ๆ ตัวรวมไปถึงมีสมาชิกจำนวนมาก

<p>ค่าที่ตั้งไว้นี้ควรตั้งให้มากที่สุดเท่าที่จะมากได้ ค่าทั่วไปแนะนำไว้ที่ 40M มีอยู่หลายวิธีในการเพิ่มค่าความจำสูงสุด กล่าวคือ:

<ol>

<li>รีคอมไพล์ PHP ใหม่ โดยเพิ่มคำสั่ง <i>--enable-memory-limit</i> ซึ่งเป็นการตั้งค่าให้ moodle กำหนดขีดจำกัดค่าสูงสุดเอง

<li>ถ้าคุณสามารถแก้ไขไฟล์  php.ini ได้ด้วยตนเองก็สามารถเปลี่ยนค่า <b>memory_limit</b> ให้เป็นค่าอื่นได้เช่น  40M แต่ถ้าไม่สามารถเปลี่ยนค่านี้ได้ด้วยตนเองให้แจ้งผู้ดูแลระบบแก้ไข

<li>ในเซิร์ฟเวอร์ PHP บางตัวคุณสามารถสร้าง ไฟล์ .htaccess ภายใต้ไดเรกทอรี moodle ซึ่งมีบรรทัดต่อไปนี้อยู่:

<p><blockquote>php_value memory_limit 40M</blockquote></p>

<p>อย่างไรก็ตามในบางเซิร์ฟเวอร์คุณไม่สามารถใช้ วิธีนี้ได้ โดยจะมีการแสดง error ขึ้นมาคุณจำเป็นต้องลบไฟล์ดังกล่าวนี้ทิ้ง
</ol>';
$string['paths'] = 'เส้นทาง';
$string['pathserrcreatedataroot'] = 'ไดเรกทอรีข้อมูล ({$a->dataroot}) ไม่สามารถสร้างขึ้นโดยการติดตั้ง';
$string['pathshead'] = 'ยืนยันเส้นทาง';
$string['pathsrodataroot'] = 'ไดเรกทอรีข้อมูลไม่สามารถเขียนได้';
$string['pathsroparentdataroot'] = 'ไดเรกทอรีหลัก ({$a->parent}) ไม่ได้เขียนได้ ไดเรกทอรีข้อมูล ({$a->dataroot}) ไม่สามารถสร้างขึ้นโดยการติดตั้ง';
$string['pathssubadmindir'] = 'เจ้าของเว็บน้อยมากที่จะใช้ / ผู้ดูแล เป็น URL ที่พิเศษสำหรับคุณในการเข้าถึงแผงควบคุมหรือบางสิ่งบางอย่าง

แต่น่าเสียดายที่การขัดแย้งนี้กับแหล่งที่ตั้งมาตรฐานสำหรับหน้าผู้ดูแลระบบ Totara

คุณสามารถแก้ไขปัญหานี้โดยการเปลี่ยนชื่อไดเรกทอรีผู้ดูแลระบบในการติดตั้ง และการวางชื่อใหม่ที่นี่ ตัวอย่างเช่น <em>totaraadmin</em> นี้จะแก้ไขปัญหาการเชื่อมโยงผู้ดูแลในระบบ Totara';
$string['pathsunsecuredataroot'] = 'สถานที่ตั้ง Dataroot ไม่ปลอดภัย';
$string['pathswrongadmindir'] = 'ชื่อผู้ดูแลไดเรกทอรีที่ไม่ได้มีอยู่';
$string['phpextension'] = 'ขยาย {$a} PHP';
$string['phpversion'] = 'PHP เวอร์ชัน';
$string['phpversionhelp'] = '<p>Totara จำเป็นต้องใช้ PHP เวอร์ชัน 4.1.0 เป็นอย่างน้อย</p>

<p>คุณกำลังใช้เวอร์ชัน {$a}</p>

<p>คุณต้องอัพเกรด  PHP หรือย้ายโฮสต์ใหม่ที่มี PHP เวอร์ชันใหม่กว่า</p>';
$string['welcomep10'] = '{$a->installername} ({$a->installerversion})';
$string['welcomep20'] = 'ท่านได้ทำการติดตั้ง<strong>{$a->packname} {$a->packversion}</strong> สำเร็จแล้ว';
$string['welcomep30'] = 'เวอร์ชั่น <strong>{$a->installername}</strong>รวมโปรแกรมสำหรับสร้างความให้กับระบบซึ่ง Totara สามารถทำงานได้';
$string['welcomep40'] = 'แพ็กเกจนี้รวม <strong>Totara {$a->moodlerelease} ({$a->moodleversion})</strong>.';
$string['welcomep50'] = 'การใช้งานโปรแกรมต่าง ๆ ในแพ็กเกจนี้สามารถทำได้โดยไม่ละเมิดสัญญานุญาตของแต่ละโปรแกรม  โปแกรม<strong>{$a->installername}</strong>เต็มรูปแบบนั้นจัดเป็นโปรแกรมประเภท
<a href="http://www.opensource.org/docs/definition_plain.html">โอเพ่นซอร์ส</a> และเผยแพร่ภายใต้สํญญานุญาต <a href="http://www.gnu.org/copyleft/gpl.html">GPL</a>';
$string['welcomep60'] = 'หน้าถัดจากนี้ไปจะเป็นการตั้งค่า Totara บนคอมพิวเตอร์คุณสามารถยอมรับค่าที่ตั้งไว้ทั้งหมดหรือเปลี่ยนแปลงให้เหมาะกับความต้องการ';
$string['welcomep70'] = 'คลิกที่ "ต่อไป" เพื่อติดตั้ง Totara ต่อไป';
$string['wwwroot'] = 'ที่อยู่ของเว็บ';
