<?php

// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Automatically generated strings for Moodle installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['admindirname'] = 'Director Admin';
$string['availablelangs'] = 'Pachete de limbă disponibile';
$string['chooselanguagehead'] = 'Selectare limbă';
$string['chooselanguagesub'] = 'Vă rugăm selectaţi limba pentru interfaţa de instalare, limba selectată va fi folosită EXCLUSIV în cadrul procedurii de instalare. Ulterior veţi putea selecta limba în care doriţi să fie afişată interfaţa.';
$string['clialreadyconfigured'] = 'Fișierul de configurare';
$string['clialreadyinstalled'] = 'Fișierul de configurare config.php există deja. Vă rugăm să folosiți dmin/cli/install_database.php to pentru a upgrada Totara pentru acest site.';
$string['cliinstallheader'] = 'Program  command line installation Totara {$a}';
$string['configfilewritten'] = 'config.php a fost creat cu succes';
$string['databasehost'] = 'Gazdă baza de date';
$string['databasename'] = 'Nume baza de date';
$string['databasetypehead'] = 'Alegere driver baza de date';
$string['dataroot'] = 'Director date';
$string['datarootpermission'] = 'Permisiuni directoare date';
$string['dbprefix'] = 'Prefix tabele';
$string['dirroot'] = 'Director Totara';
$string['environmenthead'] = 'Se verifică mediul...';
$string['environmentsub2'] = 'Fiecare versiune Totara are o anumită cerință minimă PHP și un număr de extensii PHP obligatorii.
Verificarea completă a mediului se face înainte de fiecare instalare și upgrade. Vă rugăm să contactați administratorul serverului, dacă nu știți cum se instalează noua versiune sau dacă activați extensiile PHP.';
$string['errorsinenvironment'] = 'Verificarea sistemului nu a reusit!';
$string['installation'] = 'Instalare';
$string['langdownloaderror'] = 'Pachetul pentru limba "{$a}" nu s-a putut descarca. Procesul de instalare va continua in engleza.';
$string['memorylimithelp'] = '<p>Limita PHP pentru server este setata la {$a}.</p>

<p>Acest lucru poate duce ulterior la probleme de memorie, mai ales daca sunt active multe module si multi utilizatori.</p>

<p>Recomandam configurarea PHP cu o limita mai mare de memorie, ca 40M.
 Poti realiza acest lucru prin metode diferite:</p>
 <ol>
<li>Poti recompila PHP folosind <i>--enable-memory-limit</i>.
Acest lucru va permite ca sistemul Totara sa-si seteze singur limita de memorie.</li>
<li>Daca ai acces la fisierul php.ini poti seta <b>memory_limit</b> la ceva mai mare ca 40M. Daca nu ai acces poti ruga administratorul sa faca aceasta setare.</li>
 <li>Pe unele servere poti face in directorul Totara un fisier.htaccess care sa contina linia:
<blockquote><div>php_value memory_limit 40M</div></blockquote>
 <p>Exista posibilitatea ca acest lucru sa blocheze <b>toate</b> paginile PHP (in l9oc de pagini se vor incarca erori) asa ca fisierul .htaccess o sa trebuiasca sters.</p></li>
 </ol>';
$string['paths'] = 'Căi';
$string['pathserrcreatedataroot'] = 'Folderul de date ({$a->dataroot}) nu se poate face de catre procesul de instalare.';
$string['pathshead'] = 'Confirmare căi';
$string['pathsrodataroot'] = 'Folderul de date (dataroot) nu se poate scrie.';
$string['pathsroparentdataroot'] = 'Folderul parinte ({$a->parent}) nu se poate scrie. Folderul de date ({$a->dataroot}) nu se poate face de catre procesul de instalare.';
$string['pathssubadmindir'] = 'Cateva servicii de hosting web folosesc /admin pentru a accesa un panou de control sau altceva. Acest lucru intra in conflict cu locatia standard pentru fisierele de admin Totara. Poti corecta acest lucru prin redenumirea folderului admin Totara (adauga numele aici). De exemplu: <em>totaraadmin</em>.';
$string['pathssubdataroot'] = '<p>Un director unde Totara va stoca tot conținutul unui fișier încărcat de către utilizatori.</p>
<p>Acest director trebuie să poată fi citit și scris de către utilizatrii serverului web (de obicei \'www-data\', \'nobody\', or \'apache\').</p>
<p>Nu trebuie să fie direct accesibil de pe web.</p>
<p>Dacă directorul nu există în prezent, procesul de instalare va încerca să îl creeze.</p>';
$string['pathssubdirroot'] = '<p>Calea completă către directorul care conține codul Totara .</p>';
$string['pathsunsecuredataroot'] = 'Folderul de date (dataroot) nu se afla intr-o locatie sigura';
$string['pathswrongadmindir'] = 'Folderul admin nu exista';
$string['phpextension'] = 'extensie PHP {$a}';
$string['phpversion'] = 'Versiune PHP';
$string['phpversionhelp'] = '<p>Totara necesită o versiune PHP de cel puțin  4.3.0 or 5.1.0 (5.0.x are un număr de probleme cunscute).</p>
<p>Momentan rulați versiunea {$a}</p>
<p>Trebuie să upgradați PHP sau să îl mutați pe o gazdă cu o nouă versiune de PHP!<br />
(În cazul 5.0.x puteți, de asemenea, să downgradați la versiunea 4.4.x)</p>';
$string['welcomep10'] = '{$a->installername} ({$a->installerversion})';
$string['welcomep20'] = 'Vezi aceasta pagina pentru ca ai instalat cu succes si lansat pachetul <strong>{$a->packname}{$a->packversion}</strong> in sistem. Felicitari!';
$string['welcomep30'] = 'Lansarea <strong>{$a->installername}</strong> include aplicațiile
    pentru a crea un mediu în care <strong>Totara</strong> va funcționa, și anume:';
$string['welcomep40'] = 'Pachetul include și <strong>Totara {$a->moodlerelease} ({$a->moodleversion})</strong>.';
$string['welcomep50'] = 'Folosirea tuturor aplicatiilor din acest pachet se supune licentelor lor. Pachetul complet <strong>{$a->installername}</strong> este <a href="http://www.opensource.org/docs/definition_plain.html">open source</a> si distribuit sub licenta <a href="http://www.gnu.org/copyleft/gpl.html">GPL</a>.';
$string['welcomep60'] = 'Următoarele pagini vă oferă pași ușor de urmat pentru a
   configura și seta <strong>Totara</strong> în computerul       dumneavoastră. Puteți accepta setările implicite
    sau, opțional, să le modificați pentru a corespunde nevoilor dumneavoastră.';
$string['welcomep70'] = 'Click pe butonul "Next" de mai jos pentru a continua setarea <strong>Totara</strong>.';
$string['wwwroot'] = 'Adresă Web';
