<?php

// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Automatically generated strings for Moodle installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['cannotcreatedboninstall'] = '<p>डेटाबेस नहीं बना सकते।</p>
<p>निर्दिष्ट किया गया डेटाबेस मौजूद नहीं है और दिए गए उपयोगकर्ता को डेटाबेस बनाने की अनुमति नहीं है।</p>
<p>साइट प्रशासक को डेटाबेस कॉन्फ़िगरेशन सत्यापित करना चाहिए।</p>';
$string['cannotcreatelangdir'] = 'लैंग निर्देशिका नहीं बना सकते।';
$string['cannotcreatetempdir'] = 'अस्थायी निर्देशिका नहीं बना सकते';
$string['cannotdownloadcomponents'] = 'घटकों को डाउनलोड नहीं किया जा सकता';
$string['cannotdownloadzipfile'] = 'ज़िप फ़ाइल डाउनलोड नहीं की जा सकती';
$string['cannotfindcomponent'] = 'घटक नहीं खोजा जा सका';
$string['cannotsavemd5file'] = 'md5 फ़ाइल को सहेज नहीं सकते';
$string['cannotsavezipfile'] = 'ZIP फ़ाइल को सहेज नहीं सकते';
$string['cannotunzipfile'] = 'फ़ाइल को अनझिप नहीं कर सकते';
$string['componentisuptodate'] = 'घटक अप-टू-डेट है';
$string['dmlexceptiononinstall'] = '<p>एक डेटाबेस त्रुटि हुई है [{$a->errorcode}]<br />{$a->debuginfo}</p>';
$string['downloadedfilecheckfailed'] = 'डाउनलोड की गई फ़ाइल की जांच असफल रही';
$string['invalidmd5'] = 'जांच चार गलत था - पुन: प्रयास करें';
$string['missingrequiredfield'] = 'कुछ आवश्यक फ़ील्ड अनुपलब्ध हैं';
$string['remotedownloaderror'] = '<p>आपके सर्वर पर घटक का डाउनलोड असफल रहा। कृप्या प्रॉक्सी सेटिंग्स को सत्यापित करें; PHP cURL एक्सटेंशन अत्यधिक अनुशंसित है।</p>
<p>आपको <a href="{$a->url}">{$a->url}</a> मैन्युअल रूप से फ़ाइल डाउनलोड करनी चाहिए, इसे अपने सर्वर में "{$a->dest}" पर कॉपी करें और वहां अनज़ीप करें।</p>';
$string['wrongdestpath'] = 'गलत गंतव्य पथ';
$string['wrongsourcebase'] = 'गलत स्रोत URL बेज़';
$string['wrongzipfilename'] = 'गलत ZIP फ़ाइल का नाम';
