<?php

// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Automatically generated strings for Moodle installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['admindirname'] = 'Администраторска директория';
$string['availablelangs'] = 'Налични езикови пакети';
$string['chooselanguagehead'] = 'Изберете език';
$string['chooselanguagesub'] = 'Моля, изберете език за инсталацията. Този език ще бъде, също така, език по подразбиране на сайта, но може да бъде променен и по-късно след инсталирането.';
$string['clialreadyconfigured'] = 'Конфигурационният файл config.php вече съществува. Използвайте admin/cli/install_database.php, за да инсталирате Totara за този сайт.';
$string['clialreadyinstalled'] = 'Конфигурационният файл config.php вече съществува. Използвайте admin/cli/install_database.php, за да надстроите Totara за този сайт.';
$string['databasehost'] = 'Хост на базата данни';
$string['databasename'] = 'Име на базата данни';
$string['databasetypehead'] = 'Избиране на драйвер за база данни';
$string['dataroot'] = 'Директория за данни';
$string['datarootpermission'] = 'Разрешение за директории с данни';
$string['dbprefix'] = 'Представка на таблиците';
$string['dirroot'] = 'Директория на Totara';
$string['environmenthead'] = 'Проверка на Вашата работна среда ...';
$string['environmentsub2'] = 'Всяка версия на Totara изисква някаква минимална версия на PHP и няколко необходими PHP разширения. Преди всяко инсталиране или надграждане се извършва пълна проверка на работната среда. Моля, обърнете се към администратора на сървъра ако не знаете как да инсталирате нова версия или да разрешите резширенията на PHP.';
$string['errorsinenvironment'] = 'Проверката на роботната среда е прекратена!';
$string['installation'] = 'Инсталиране';
$string['langdownloaderror'] = 'За съжаление езикът "{$a}" не може да бъде изтеглен. Инсталирането ще продължи на английски.';
$string['memorylimithelp'] = '<p>Лимитът за PHP паметта на вашия сървър в момента е зададен на {$a}.</p>

<p>Това може да доведе до проблеми с паметта в Totara по-късно, особено при
 наличие на много активирани модули и/или много потребители.</p>

<p>Препоръчваме ви да конфигурирате PHP с по-висок лимит, ако е възможно, като например 40M.
 Има няколко начина да направите това, които можете да изпробвате:</p>
<ol>
<li>Ако можете, прекомпилирайте PHP с <i>--enable-memory-limit</i>.
 Това ще позволи на Totara да зададе свой лимит на паметта.</li>
<li>Ако имате достъп до файла php.ini, можете да промените настройката <b>memory_limit</b>
 на приблизително 40M.  Ако нямате такъв достъп, можете
 да помолите администратора си да го направи.</li>
<li>На някои PHP сървъри можете да създадете файл .htaccess в директорията на Totara,
    който съдържа този ред:
 <blockquote><div>php_value memory_limit 40M</div></blockquote>
 <p>Въпреки това на някои сървъри това ще попречи на <b>всички</b> PHP страници да работят
 (ще виждате грешки, когато преглеждате страници), така че ще трябва да премахнете файла .htaccess.</p></li>
</ol>';
$string['paths'] = 'Пътища';
$string['pathserrcreatedataroot'] = 'Директорията с данни ({$a->dataroot}) не може да бъде създадена от инсталатора.';
$string['pathshead'] = 'Потвърждаване на пътищата';
$string['pathsrodataroot'] = 'В директорията dataroot не може да се записва.';
$string['pathsroparentdataroot'] = 'Директория ({$a->parent}) не е разрешена за запис и директорията за данни ({$a->dataroot}) не може да бъде създадена от инсталатора.';
$string['pathssubadmindir'] = 'Много малък брой уеб хостове използват /admin като специален URL адрес, чрез който да имате достъп до
контролен панел или нещо подобно.  За съжаление, това противоречи със стандартното местоположение за администраторските страници на Totara.  Можете да коригирате това, като
преименувате администраторската директория в инсталацията и поставите новото име тук.  Например: <em>totaraadmin</em>. Това ще коригира администраторските връзки в Totara.';
$string['pathssubdataroot'] = 'Тази директория е място, където Totara, записва качваните файлове. Тази директория трябва да е достъпна за четене И ЗА ЗАПИС от потребителя на интернет сървъра (обикновено \'nobody\' или \'apache\'), но не трябва да е достъпна пряко през Интернет. Инталаторът ще се опита да създаде директорията, ако тя не съществува.';
$string['pathssubdirroot'] = 'Пълен път до директорията на Totara.';
$string['pathssubwwwroot'] = 'Пълен интернет адрес, на който ще се отваря Totara. Не е възможно Totara да се отваря чрез различни адреси. Ако Вашият сайт има няколко адреса трябва на всеки от другите адреси да направите пренасочване към този. Ако Вашият сайт се отваря както глобално от Интернет, така и от локална мрежа, настройте DNS, така че потребителите от локалната мрежа също да могат да ползват глобалния адрес. Ако адресът не е коректен, моля, променете адреса в браузъра си и започнете инсталирането с правилния адрес.';
$string['pathsunsecuredataroot'] = 'Местоположението на dataroot не е защитено';
$string['pathswrongadmindir'] = 'Администраторската директория не съществува';
$string['phpextension'] = '{$a} разширение на PHP';
$string['phpversion'] = 'Версия на PHP';
$string['phpversionhelp'] = '<p>Totara изисква версия на PHP най-малко 4.3.0 или 5.1.0 (5.0.x има значителен брой известни проблеми).</p> <p>Вие използвате в момента версия {$a}</p> <p>Трябва да обновите PHP или да се преместите на нов хост (сървър) с по-нова версия на PHP!<br /> (В случая с 5.0.x може да опитате да инсталирате по-старата версия 4.4.x)</p>';
$string['welcomep10'] = '{$a->installername} ({$a->installerversion})';
$string['welcomep20'] = 'Виждате тази страница, тъй като сте инсталирали успешно и
 сте стартирали пакета <strong>{$a->packname} {$a->packversion}</strong> на вашия компютър. Поздравления!';
$string['welcomep40'] = 'Пакетът включва също <strong>Totara {$a->moodlerelease} ({$a->moodleversion})</strong>.';
$string['welcomep50'] = 'Използването на всички приложения в този пакет се управлява от съответните им
 лицензи. Пълният пакет на <strong>{$a->installername}</strong> е
 <a href="http://www.opensource.org/docs/definition_plain.html">с отворен код</a> и се разпространява
  под <a href="http://www.gnu.org/copyleft/gpl.html">GPL</a> лиценза.';
$string['wwwroot'] = 'Уеб адрес';
