<?php

// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Automatically generated strings for Moodle installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['cannotcreatedboninstall'] = '<p>Datubāzi nevar izveidot.</p>
<p>Norādītā datubāze neeksistē, un attiecīgajam lietotājam nav atļaujas izveidot datubāzi.</p>
<p>Vietnes administratoram ir nepieciešams verificēt datubāzes konfigurāciju.</p>';
$string['cannotcreatelangdir'] = 'Nevar izveidot valodas direktoriju';
$string['cannotcreatetempdir'] = 'Nevar izveidot pagaidu direktoriju';
$string['cannotdownloadcomponents'] = 'Nevar lejupielādēt komponentus';
$string['cannotdownloadzipfile'] = 'Nevar lejupielādēt ZIP failu';
$string['cannotfindcomponent'] = 'Nevar atrast komponentu';
$string['cannotsavemd5file'] = 'Nevar saglabāt md5 failu';
$string['cannotsavezipfile'] = 'Nevar saglabāt ZIP failu';
$string['cannotunzipfile'] = 'Nevar atzipot failu';
$string['componentisuptodate'] = 'Komponents atbilst visjaunākajai versijai.';
$string['dmlexceptiononinstall'] = '<p>Radās datubāzes kļūda [{$a->errorcode}].<br />{$a->debuginfo}</p>';
$string['downloadedfilecheckfailed'] = 'Lejupielādētā faila pārbaudes rezultāts nesekmīgs.';
$string['invalidmd5'] = 'Pārbaudītais mainīgais bija nepareizs - mēģiniet vēlreiz';
$string['missingrequiredfield'] = 'Trūkst kāda nepieciešamā lauka';
$string['remotedownloaderror'] = '<p>Komponenta lejupielāde uz jūsu serveri neizdevās. Pārbaudiet starpniekservera iestatījumus; ļoti ieteicams izmantot PHP cURL paplašinājumu.</p>
<p>Jums ir nepieciešams <a href="{$a->url}">{$a->url}</a> failu lejupielādēt manuāli, kopēt to uz “{$a->dest}” jūsu serverī un tur to izgūt no ZIP arhīva.</p>';
$string['wrongdestpath'] = 'Nepareizs mērķa ceļš.';
$string['wrongsourcebase'] = 'Nepareiza avota URL bāze.';
$string['wrongzipfilename'] = 'Nepareizs ZIP faila nosaukums.';
