<?php

// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Automatically generated strings for Moodle installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['admindirname'] = 'Direktori Admin';
$string['availablelangs'] = 'Paket bahasa yang tersedia';
$string['chooselanguagehead'] = 'Pilih bahasa';
$string['chooselanguagesub'] = 'Harap pilih bahasa untuk instalasi. Bahasa ini juga akan digunakan sebagai bahasa default untuk situs, meskipun bahasa ini bisa diubah nanti.';
$string['databasehost'] = 'Host basis data';
$string['databasename'] = 'Nama basis data';
$string['databasetypehead'] = 'Pilih driver basis data';
$string['dataroot'] = 'Direktori data';
$string['datarootpermission'] = 'Izin direktori data';
$string['dbprefix'] = 'Awalan tabel';
$string['environmenthead'] = 'Memeriksa lingkungan Anda ...';
$string['errorsinenvironment'] = 'Pemeriksaan lingkungan gagal!';
$string['installation'] = 'Instalasi';
$string['langdownloaderror'] = 'Sayangnya bahasa "{$a}" tidak dapat diunduh. Proses instalasi akan dilanjutkan dalam bahasa Inggris.';
$string['memorylimithelp'] = '<p>Batas memori PHP untuk server Anda saat ini diatur ke {$a}.</p>

<p>Hal ini dapat menyebabkan Totara memiliki masalah memori di kemudian haru, khususnya
   jika Anda memiliki modul yang diaktifkan dan/atau banyak pengguna.</p>

<p>Kami rekomendasikan agar Anda mengonfigurasi PHP dengan batas yang lebih tinggi jika memungkinkan, misalnya dengan 40M.
   Ada beberapa cara untuk melakukan hal ini yang dapat Anda coba:</p>
<ol>
<li>jika Anda dapat mengompilasi ulang PHP dengan <i>--aktifkan-batas-memori</i>.
    Hal ini akan mengizinkan Totar untuk mengatur batas memori itu sendiri.</li>
<li>Jika Anda memiliki akses ke file php.ini, Anda dapat mengubah pengaturan <b>memory_limit</b>
    di sana menjadi nilai, misalnya dengan 40M.  Jika Anda tidak memiliki akses, Anda mungkin
    dapat meminta administrator Anda untuk melakukan hal ini bagi Anda.</li>
<li>Pada beberapa server PHP Anda dapat membuat file .htaccess di dalam direktori Totara
    yang mengandung kalimat ini:
    <blockquote><div>php_value memory_limit 40M</div></blockquote>
    <p>Namun, pada beberapa server, hal ini akan mencegah <b>semua</b> halaman PHP untuk berfungsi
    (Anda akan melihat kesalahan saat Anda melihat ke halaman tersebut) jadi Anda akan harus menghapus file .htaccess tersebut.</p></li>
</ol>';
$string['paths'] = 'Jalur';
$string['pathserrcreatedataroot'] = 'Direktori data ({$a->dataroot}) tidak dapat dibuat oleh penginstal.';
$string['pathshead'] = 'Konfirmasikan jalur';
$string['pathsrodataroot'] = 'Direktori dataroot tidak dapat ditulis.';
$string['pathsroparentdataroot'] = 'Direktori induk ({$a->parent}) tidak dapat ditulis. Direktori data ({$a->dataroot}) tidak dapat dibuat oleh penginstal.';
$string['pathssubadmindir'] = 'Sangat sedikit webhost menggunakan /admin sebagai URL khusus agar Anda bisa mengakses
panel kontrol atau sesuatu. Sayangnya hal ini konflik dengan lokasi standar untuk halaman admin Totara. Anda dapat memperbaiki ini dengan cara mengganti nama direktori admin di instalasi Anda, dan meletakkan nama baru di sini. Misalnya: <em>totaraadmin</em>. Hal ini akan memperbaiki tautan admin di Totara.';
$string['pathsunsecuredataroot'] = 'Lokasi dataroot tidak aman';
$string['pathswrongadmindir'] = 'Direktori admin tidak ada';
$string['phpextension'] = 'Ekstensi PHP {$a}';
$string['phpversion'] = 'Versi PHP';
$string['welcomep10'] = '{$a->installername} ({$a->installerversion})';
$string['welcomep20'] = 'Anda melihat halaman ini karena Anda telah berhasil menginstal dan meluncurkan paket <strong>{$a->packname} {$a->packversion}</strong> di komputer Anda. Selamat!';
$string['welcomep50'] = 'Penggunaan semua aplikasi di dalam paket ini diatur oleh lisensinya
    yang sesuai. Paket <strong>{$a->installername}</strong> lengkap adalah
    <a href="http://www.opensource.org/docs/definition_plain.html">open source</a> dan didistribusikan
    di bawah lisensi <a href="http://www.gnu.org/copyleft/gpl.html">GPL</a>.';
$string['wwwroot'] = 'Alamat web';
