<?php

// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Automatically generated strings for Moodle installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['cannotcreatedboninstall'] = '<p style=";text-align:right;direction:rtl"> لا يمكن إنشاء قاعدة البيانات. </p><p style=";text-align:right;direction:rtl"> عدم وجود قاعدة بيانات محددة ومستخدم معين ليس لديه صلاحية إنشاء قاعدة البيانات. </p><p style=";text-align:right;direction:rtl"> المسؤول عن الموقع يجب أن يتحقق من تكوين قاعدة البيانات. </p>';
$string['cannotcreatelangdir'] = 'لا يمكن إنشاء مجلد اللغة';
$string['cannotcreatetempdir'] = 'لا يمكن إنشاء المجلد المؤقت';
$string['cannotdownloadcomponents'] = 'لم يتم تحميل العناصر';
$string['cannotdownloadzipfile'] = 'لم يتم تحميل الملف المضغوط';
$string['cannotfindcomponent'] = 'لم يتم العثور على المكون';
$string['cannotsavemd5file'] = 'لم يتم حفظ ملف  md5';
$string['cannotsavezipfile'] = 'لم يتم حفظ الملف المضغوط';
$string['cannotunzipfile'] = 'لم يتم فك الملف المضغوط';
$string['componentisuptodate'] = 'العنصر محدث';
$string['dmlexceptiononinstall'] = '<p style=";text-align:right;direction:rtl"> حدث خطأ في قاعدة البيانات [{$a->errorcode}]. <br /> {$a->debuginfo} </p>';
$string['downloadedfilecheckfailed'] = 'التحقق من تنزيل الملف قد فشل';
$string['invalidmd5'] = 'متغير التحقق كان خطأ - حاول مرة أخرى';
$string['missingrequiredfield'] = 'بعض الحقول المطلوبة مفقودة';
$string['remotedownloaderror'] = 'فشل في تحميل المكونات لخادمك , الرجاء التحقق من اعدادات الوكيل . يُنصح بشدة بالامتدادات PHP cURL .n<br /><br /> يجب عليك تحميل ملف <a href="{$a->url}">{$a->url}</a> يدوياً.نسخة الى "{$a->dest}"  الخادم الخاص بك وفكه هناك.';
$string['wrongdestpath'] = 'مسار الوجهة خطأ';
$string['wrongsourcebase'] = 'قاعدة مصدر الرابط خطأ';
$string['wrongzipfilename'] = 'إسم الملف المضغوط خطأ';
